import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {policySchema,validateRevision,selectPolicies,lifecycle,effectiveDateLabel,regions,countries,countryOf,keyDate} from '../lib/domain/model.ts';
import {discovery,discoveryForYear} from '../lib/domain/coverage.ts';
const seed=JSON.parse(readFileSync(new URL('../data/seed.json',import.meta.url),'utf8'));
test('all researched records satisfy evidence and date contracts',()=>{for(const p of seed)assert.doesNotThrow(()=>policySchema.parse(p));});
test('pending is excluded from default adopted view',()=>{const r=selectPolicies(seed,'adopted','all','all','');assert.equal(r.length,20);assert(r.every(p=>p.phase==='adopted'));});
test('federal policy is not silently counted as state policy',()=>{assert.equal(selectPolicies(seed,'all','DE-HE','all','').length,2);assert.equal(selectPolicies(seed,'all','DE-BE','all','').length,1);});
test('scheduled future vote cannot count as adoption',()=>{const p=structuredClone(seed.find((p:any)=>p.id==='de-carf-agreement-2026'));p.phase='adopted';assert.equal(policySchema.safeParse(p).success,false);});
test('historical evidence cannot be rewritten or deleted',()=>{const p=seed[0],next=structuredClone(p);next.events[0].detail='rewritten';assert.throws(()=>validateRevision(p,next),/immutable/);next.events=[];assert.throws(()=>validateRevision(p,next),/immutable/);});
test('date validation rejects impossible dates and unsupported future facts',()=>{const p=structuredClone(seed[0]);p.events[0].date='2026-02-30';assert.equal(policySchema.safeParse(p).success,false);p.events[0].date='2027-01-01';assert.equal(policySchema.safeParse(p).success,false);});
test('a milestone arriving does not turn a pending bill into law',()=>{const p=seed.find((p:any)=>p.id==='de-carf-agreement-2026');assert.equal(lifecycle(p,'2026-10-10'),'已过计划日期 · 结果待核实');});
test('text searches include official identifiers',()=>{assert.equal(selectPolicies(seed,'all','all','all','21/5752').length,1);});

test('expiry is not mistaken for staged implementation',()=>{const p=seed.find((p:any)=>p.id==='de-fuel-relief-2026');assert.equal(lifecycle(p,'2026-10-02'),'已生效 · 临时措施');});

test('expired temporary measure displays uncertainty instead of silently staying active',()=>{const p=seed.find((p:any)=>p.id==='de-fuel-relief-2026');assert.equal(lifecycle(p,'2027-01-02'),'已通过 · 期限已到，后续待核实');});

test('every state has an evidenced record and an official discovery entry',()=>{for(const r of regions.filter(r=>countryOf(r.id)==='DE')){assert(seed.some((p:any)=>p.region===r.id),r.id);assert(discovery.some(d=>d.region===r.id),r.id);}});
test('unknown and future voting evidence cannot become invented results',()=>{const p=structuredClone(seed[0]);p.politics.votes[0].date='2027-01-01';assert.equal(policySchema.safeParse(p).success,false);p.politics.votes[0].date='2025-06-26';p.politics.proposedBy.sourceId='unknown';assert.equal(policySchema.safeParse(p).success,false);p.politics.proposedBy.sourceId='rent-vote';assert.equal(policySchema.parse(p).politics?.votes?.[0].counts,null);});
test('rules require cited evidence and effective start is distinct from expiry',()=>{const p=structuredClone(seed.find((p:any)=>p.id==='he-rent-protection-2025'));assert.equal(p.effectiveDate,'2025-11-18');assert.equal(p.nextDate,'2026-11-25');assert.match(p.dateExplanation,/2020年11月26日/);assert.equal(effectiveDateLabel(p),'本次改动开始生效');p.rules[0].sourceId='missing';assert.equal(policySchema.safeParse(p).success,false);});
test('adoption with unknown legal commencement remains explicit',()=>{const p=seed.find((p:any)=>p.id==='th-kita-third-free-year-2026');assert.equal(p.effectiveDate,null);assert.equal(p.phase,'adopted');assert.equal(effectiveDateLabel(p),'最近已确认进展');assert.match(lifecycle(p,'2026-10-02'),/生效日未确认/);});
test('annual official indexes use the request year, never the Worker module clock',()=>{for(const year of [2026,2027]){const entries=discoveryForYear(year).filter(d=>d.url.includes('/'+year));assert.equal(entries.length,2);for(const d of entries){assert(d.url.includes('/'+year));assert(d.title.includes(String(year)));}}assert(!discovery.some(d=>d.url.includes('1970')));});

import {intakeBatchSchema,scanSchema,coverageRows,validateScanTime} from '../lib/domain/intake.ts';
import {readFilters,filterSearch} from '../lib/domain/filters.ts';
const baseline=JSON.parse(readFileSync(new URL('../data/forward-baseline.json',import.meta.url),'utf8'));
test('forward baseline preserves separate laws within the same gazette and all candidates',()=>{const b=intakeBatchSchema.parse(baseline);assert.equal(new Set(b.records.map(r=>r.id)).size,b.records.length);const hh=b.records.filter(r=>r.region==='DE-HH');assert.equal(hh.length,3);assert.equal(new Set(hh.map(r=>r.url)).size,1);for(const scan of b.scans)for(const id of scan.recordIds)assert(b.records.some(r=>r.id===id));assert(b.scans.every(s=>s.status!=='complete'));});
test('multi-tag filtering is OR within tags, AND with region and phase',()=>{const rent=selectPolicies(seed,'all','all','all','',['租房']);assert(rent.length>5);assert(rent.every(p=>p.tags?.includes('租房')));const investment=selectPolicies(seed,'all','all','all','',['投资']);assert.equal(investment.length,3);assert.equal(selectPolicies(seed,'all','all','all','',['租房','投资']).length,rent.length+investment.length);assert.equal(selectPolicies(seed,'adopted','DE','all','',['投资']).length,1);assert.equal(selectPolicies(seed,'all','all','all','',['不存在']).length,0);});
test('new categories are accepted and missing tags never exclude default results',()=>{const p=structuredClone(seed[0]);p.topic='农业与食品';p.tags=['农业','食品安全'];assert(policySchema.safeParse(p).success);delete p.tags;assert.equal(selectPolicies([p],'all','all','all','').length,1);});
test('filter URL round-trip preserves multilingual categories and policy detail',()=>{const state={view:'all',country:'DE',region:'DE-HE',query:'租金 & 税',tags:['租房','投资']};const url=filterSearch('?policy=test',state);assert.deepEqual(readFilters(url),state);assert.equal(new URLSearchParams(url).get('policy'),'test');assert.equal(readFilters('?region=invalid&view=evil').region,'all');});
test('complete scans require enumeration, reconciliation and a closed day',()=>{const source=baseline.scans[0].sourceUrl;const complete={...baseline.scans[0],sourceUrl:source,checkedAt:'2026-10-03T01:00:00Z',status:'complete',allPagesChecked:true,totalListed:0,recordIds:[],excluded:[]};assert(scanSchema.safeParse(complete).success);assert(!scanSchema.safeParse({...complete,allPagesChecked:false}).success);assert(!scanSchema.safeParse({...complete,totalListed:1}).success);assert.throws(()=>validateScanTime(complete,new Date('2026-10-02T20:00:00Z')),/ongoing|future/);assert.doesNotThrow(()=>validateScanTime(complete,new Date('2026-10-03T20:00:00Z')));});
test('later successful scans cannot skip an earlier date gap',()=>{const base=scanSchema.parse({...baseline.scans[0],status:'complete',allPagesChecked:true,totalListed:0,recordIds:[],excluded:[]});const later={...base,id:'later',windowStart:'2026-10-04',windowEnd:'2026-10-05'};let c=coverageRows([later],2026).find(c=>c.url===base.sourceUrl)!;assert.equal(c.coveredThrough,null);c=coverageRows([base,later],2026).find(c=>c.url===base.sourceUrl)!;assert.equal(c.coveredThrough,'2026-10-02');const fill={...base,id:'fill',windowStart:'2026-10-03',windowEnd:'2026-10-03'};assert.equal(coverageRows([base,later,fill],2026).find(c=>c.url===base.sourceUrl)!.coveredThrough,'2026-10-05');assert.equal(coverageRows([{...base,status:'partial'}],2026).find(c=>c.url===base.sourceUrl)!.coveredThrough,null);});
test('every region belongs to a configured country',()=>{for(const r of regions)assert(countries.some(c=>c.id===countryOf(r.id)),r.id);assert.equal(readFilters('?region=DE-HE').country,'DE');assert.equal(readFilters('?country=XX').country,countries[0].id);});
test('key date prefers a near-term next step over a distant expiry',()=>{const p=structuredClone(seed[0]);p.effectiveDate='2025-07-23';p.nextDate='2029-12-31';p.nextLabel='期限结束';assert.equal(keyDate(p,'2026-10-03').kind,'effective');p.nextDate='2026-10-08';assert.deepEqual(keyDate(p,'2026-10-03'),{date:'2026-10-08',label:'期限结束',kind:'next'});p.effectiveDate=null;p.nextDate='2029-12-31';assert.equal(keyDate(p,'2026-10-03').kind,'next');});

test('refresh preserves every selected category, including crypto selected thirteenth',()=>{
 const tags=['工资','工作','公共采购','公共服务','公务员','环境','建筑','交通','教师','教育','科研','能源','加密资产'];
 const before={view:'all',country:'DE',region:'all',query:'',tags};
 const after=readFilters(filterSearch('',before));
 assert.deepEqual(after,before);
 assert.deepEqual(selectPolicies(seed,after.view,after.region,'all',after.query,after.tags),selectPolicies(seed,before.view,before.region,'all',before.query,before.tags));
});
