// Frozen compatibility vocabulary for saved schema-2/3 records. Never infer new status from prose.
export const legacyStatus = {
  "已生效": "adopted",
  "分步生效": "phased",
  "已通过 · 开始实施": "adopted",
  "已生效 · 临时措施": "adopted",
  "拟议修订": "pending",
  "议案已提出 · 后续待核实": "pending",
  "已排入表决议程": "pending",
  "已生效 · 分步实施": "phased",
  "已生效 · 适用有争议": "adopted",
  "已通过 · 第三年免费尚未开始": "adopted",
  "议会一读已转交委员会 · 已排入表决议程": "pending",
  "委员会建议否决 · 10月8日全会待表决": "pending",
  "已列入10月8日21:25表决议程": "pending",
  "已公布 · 2026年10月3日生效": "adopted",
  "既有补助 · 说明已更新": "existing",
  "已实施": "adopted",
  "申请安排已公布": "adopted",
  "后续决定待核实": "pending",
  "服务已恢复": "adopted",
  "拨款已通过": "adopted",
  "安排已公布": "adopted",
  "本轮申请已结束": "application_closed",
  "提案待审议": "pending",
  "已通过 · 2026年12月首次付款": "adopted",
  "已通过 · 待生效": "adopted",
  "尚未通过": "pending",
  "已通过 · 预计2027年实施": "adopted",
  "方案公布 · 最终决定待核实": "pending",
  "已公布 · 生效日未确认": "adopted"
} as const;
export const legacyNextKind = {
  "现行条例到期；需核实是否已有接续条例": "expiry",
  "临时减税期限结束": "expiry",
  "本次延长的新租约租金限制期限结束": "expiry",
  "本条例规定的有效期结束": "expiry",
  "本条例到期；接续草案仍需通过": "expiry",
  "本轮条例期限结束": "expiry",
  "本版条例有效期结束；届时核实有无接续规定": "expiry",
  "本版租金刹车条例到期，需核实接续条例": "expiry",
  "申请截止": "deadline",
  "普通组申请期限结束": "deadline",
  "征求意见截止": "deadline",
  "本轮奖项申请截止": "deadline"
} as const;
