// ISO 3166-2: 50 states and the District of Columbia (a federal district).
export const americanRegions = [
  {"id":"US-AL","name":"阿拉巴马","en":"Alabama","de":"Alabama","originalName":"Alabama","originalLanguage":"en"},
  {"id":"US-AK","name":"阿拉斯加","en":"Alaska","de":"Alaska","originalName":"Alaska","originalLanguage":"en"},
  {"id":"US-AZ","name":"亚利桑那","en":"Arizona","de":"Arizona","originalName":"Arizona","originalLanguage":"en"},
  {"id":"US-AR","name":"阿肯色","en":"Arkansas","de":"Arkansas","originalName":"Arkansas","originalLanguage":"en"},
  {"id":"US-CA","name":"加利福尼亚","en":"California","de":"California","originalName":"California","originalLanguage":"en"},
  {"id":"US-CO","name":"科罗拉多","en":"Colorado","de":"Colorado","originalName":"Colorado","originalLanguage":"en"},
  {"id":"US-CT","name":"康涅狄格","en":"Connecticut","de":"Connecticut","originalName":"Connecticut","originalLanguage":"en"},
  {"id":"US-DE","name":"特拉华","en":"Delaware","de":"Delaware","originalName":"Delaware","originalLanguage":"en"},
  {"id":"US-DC","name":"华盛顿特区","en":"District of Columbia","de":"District of Columbia","originalName":"District of Columbia","originalLanguage":"en"},
  {"id":"US-FL","name":"佛罗里达","en":"Florida","de":"Florida","originalName":"Florida","originalLanguage":"en"},
  {"id":"US-GA","name":"佐治亚","en":"Georgia","de":"Georgia","originalName":"Georgia","originalLanguage":"en"},
  {"id":"US-HI","name":"夏威夷","en":"Hawaii","de":"Hawaii","originalName":"Hawaii","originalLanguage":"en"},
  {"id":"US-ID","name":"爱达荷","en":"Idaho","de":"Idaho","originalName":"Idaho","originalLanguage":"en"},
  {"id":"US-IL","name":"伊利诺伊","en":"Illinois","de":"Illinois","originalName":"Illinois","originalLanguage":"en"},
  {"id":"US-IN","name":"印第安纳","en":"Indiana","de":"Indiana","originalName":"Indiana","originalLanguage":"en"},
  {"id":"US-IA","name":"艾奥瓦","en":"Iowa","de":"Iowa","originalName":"Iowa","originalLanguage":"en"},
  {"id":"US-KS","name":"堪萨斯","en":"Kansas","de":"Kansas","originalName":"Kansas","originalLanguage":"en"},
  {"id":"US-KY","name":"肯塔基","en":"Kentucky","de":"Kentucky","originalName":"Kentucky","originalLanguage":"en"},
  {"id":"US-LA","name":"路易斯安那","en":"Louisiana","de":"Louisiana","originalName":"Louisiana","originalLanguage":"en"},
  {"id":"US-ME","name":"缅因","en":"Maine","de":"Maine","originalName":"Maine","originalLanguage":"en"},
  {"id":"US-MD","name":"马里兰","en":"Maryland","de":"Maryland","originalName":"Maryland","originalLanguage":"en"},
  {"id":"US-MA","name":"马萨诸塞","en":"Massachusetts","de":"Massachusetts","originalName":"Massachusetts","originalLanguage":"en"},
  {"id":"US-MI","name":"密歇根","en":"Michigan","de":"Michigan","originalName":"Michigan","originalLanguage":"en"},
  {"id":"US-MN","name":"明尼苏达","en":"Minnesota","de":"Minnesota","originalName":"Minnesota","originalLanguage":"en"},
  {"id":"US-MS","name":"密西西比","en":"Mississippi","de":"Mississippi","originalName":"Mississippi","originalLanguage":"en"},
  {"id":"US-MO","name":"密苏里","en":"Missouri","de":"Missouri","originalName":"Missouri","originalLanguage":"en"},
  {"id":"US-MT","name":"蒙大拿","en":"Montana","de":"Montana","originalName":"Montana","originalLanguage":"en"},
  {"id":"US-NE","name":"内布拉斯加","en":"Nebraska","de":"Nebraska","originalName":"Nebraska","originalLanguage":"en"},
  {"id":"US-NV","name":"内华达","en":"Nevada","de":"Nevada","originalName":"Nevada","originalLanguage":"en"},
  {"id":"US-NH","name":"新罕布什尔","en":"New Hampshire","de":"New Hampshire","originalName":"New Hampshire","originalLanguage":"en"},
  {"id":"US-NJ","name":"新泽西","en":"New Jersey","de":"New Jersey","originalName":"New Jersey","originalLanguage":"en"},
  {"id":"US-NM","name":"新墨西哥","en":"New Mexico","de":"New Mexico","originalName":"New Mexico","originalLanguage":"en"},
  {"id":"US-NY","name":"纽约","en":"New York","de":"New York","originalName":"New York","originalLanguage":"en"},
  {"id":"US-NC","name":"北卡罗来纳","en":"North Carolina","de":"North Carolina","originalName":"North Carolina","originalLanguage":"en"},
  {"id":"US-ND","name":"北达科他","en":"North Dakota","de":"North Dakota","originalName":"North Dakota","originalLanguage":"en"},
  {"id":"US-OH","name":"俄亥俄","en":"Ohio","de":"Ohio","originalName":"Ohio","originalLanguage":"en"},
  {"id":"US-OK","name":"俄克拉荷马","en":"Oklahoma","de":"Oklahoma","originalName":"Oklahoma","originalLanguage":"en"},
  {"id":"US-OR","name":"俄勒冈","en":"Oregon","de":"Oregon","originalName":"Oregon","originalLanguage":"en"},
  {"id":"US-PA","name":"宾夕法尼亚","en":"Pennsylvania","de":"Pennsylvania","originalName":"Pennsylvania","originalLanguage":"en"},
  {"id":"US-RI","name":"罗得岛","en":"Rhode Island","de":"Rhode Island","originalName":"Rhode Island","originalLanguage":"en"},
  {"id":"US-SC","name":"南卡罗来纳","en":"South Carolina","de":"South Carolina","originalName":"South Carolina","originalLanguage":"en"},
  {"id":"US-SD","name":"南达科他","en":"South Dakota","de":"South Dakota","originalName":"South Dakota","originalLanguage":"en"},
  {"id":"US-TN","name":"田纳西","en":"Tennessee","de":"Tennessee","originalName":"Tennessee","originalLanguage":"en"},
  {"id":"US-TX","name":"得克萨斯","en":"Texas","de":"Texas","originalName":"Texas","originalLanguage":"en"},
  {"id":"US-UT","name":"犹他","en":"Utah","de":"Utah","originalName":"Utah","originalLanguage":"en"},
  {"id":"US-VT","name":"佛蒙特","en":"Vermont","de":"Vermont","originalName":"Vermont","originalLanguage":"en"},
  {"id":"US-VA","name":"弗吉尼亚","en":"Virginia","de":"Virginia","originalName":"Virginia","originalLanguage":"en"},
  {"id":"US-WA","name":"华盛顿州","en":"Washington","de":"Washington","originalName":"Washington","originalLanguage":"en"},
  {"id":"US-WV","name":"西弗吉尼亚","en":"West Virginia","de":"West Virginia","originalName":"West Virginia","originalLanguage":"en"},
  {"id":"US-WI","name":"威斯康星","en":"Wisconsin","de":"Wisconsin","originalName":"Wisconsin","originalLanguage":"en"},
  {"id":"US-WY","name":"怀俄明","en":"Wyoming","de":"Wyoming","originalName":"Wyoming","originalLanguage":"en"},
];
